<?php 

//ModelObject Constants
define("MODELOBJECT_DEFAULT_ID", 0);
define("MODELOBJECT_DEFAULT_SORTVALUE", 999);
define("MODELOBJECT_UUID_INSTANCE_PREFIX", "DEV_INSTANCE");

//Participant Status Constants.
define("PARTICIPANT_PARTICIPANTSTATUS_WELL", 1);
define("PARTICIPANT_PARTICIPANTSTATUS_WELL-AT-RISK", 2);
define("PARTICIPANT_PARTICIPANTSTATUS_UNWELL", 3);
define("PARTICIPANT_PARTICIPANTSTATUS_COVID-CONFIRMED", 4);
define("PARTICIPANT_PARTICIPANTSTATUS_HOSPITALIZED-WITH-COVID", 5);
define("PARTICIPANT_PARTICIPANTSTATUS_HOSPITALIZED-WITHOUT-COVID", 6);
?>